create table if not exists public.images (
    id bigint generated by default as identity primary key,
    file_name text not null,
    title text not null,
    description text,
    bucket_path text not null unique,
    is_hidden boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.tags (
    id bigint generated by default as identity primary key,
    name text not null unique,
    created_at timestamptz not null default now()
);

create table if not exists public.image_tags (
    image_id bigint not null references public.images(id) on delete cascade,
    tag_id bigint not null references public.tags(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (image_id, tag_id)
);

create index if not exists idx_images_visibility on public.images (is_hidden);
create index if not exists idx_image_tags_tag_id on public.image_tags (tag_id);
create index if not exists idx_image_tags_image_id on public.image_tags (image_id);
