spring.application.name=gallery-project
supabase.bucket-name=${SUPABASE_BUCKET_NAME:image-gallery}
supabase.db-name=${SUPABASE_DB_NAME:images}
supabase.url=${SUPABASE_URL:https://jkrskamjvxhyfjcrbhcr.supabase.co}
supabase.api-key=${SUPABASE_API_KEY:}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${CLERK_JWKS_URI:https://example.clerk.accounts.dev/.well-known/jwks.json}
security.admin-user-ids=${ADMIN_USER_IDS:}
