spring.application.name=gallery-project
supabase.bucket-name=${SUPABASE_BUCKET_NAME:image-gallery}
supabase.db-name=${SUPABASE_DB_NAME:images}
supabase.url=${SUPABASE_URL:https://jkrskamjvxhyfjcrbhcr.supabase.co}
supabase.api-key=${SUPABASE_API_KEY:}
